### ISSUE TITLE
Strange issue with squished graphs when you switch tabs

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#544] opened 2022-01-31 11:16 UTC
watch this video.
Notice what happens when I come back from Locations tab to My Activity tab the second time AFTER having Run location observations. The graphs get squished.

https://user-images.githubusercontent.com/1473244/151784435-9990a74f-6c73-4869-9680-0b82d9b7c21a.mov

**Comment by valentinoli** [comment] 2022-01-31 11:59
@fquellec we should check if this has been fixed in #535

**Comment by alexbfree** [comment] 2022-01-31 15:06
> @fquellec we should check if this has been fixed in #535

if that has already been merged/deployed then no it is still present; tested this on the newly deployed test instance today lunchtime.

**Comment by alexbfree** [comment] 2022-01-31 15:07
![Screenshot 2022-01-31 at 15 05 24](https://user-images.githubusercontent.com/1473244/151818151-42f8210b-e0c5-4bef-bc20-4a23ea22a26a.png)

Another similar weirdness seen on same page just now (on digipower instance)

**Comment by fquellec** [comment] 2022-03-07 08:54
Sorry, long time no see :) I just checked this problem, it's unfortunately introduced with the use of tabs, to define the layout, sizes of each graphic we rely on the `VRow` and `VCol` vuetify grid system, then we need a way to pass these widths to the graph library, so we define the sizes as below: 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/17878016/156997911-6e8465ca-1110-4df9-b0ca-851dfb3f02e2.png">

The problem is that if the drawViz function is called before we actually render the tab, the width will be 0. This cannot be fixed by only setting the tabs to eager mode since if this only works the first time we run a file.... 
Maybe we could rerun the graphics every time we enter a tab? what do you think @valentinoli?

**Closed** 2022-03-28 08:16 UTC
Labels: bug, digipower-priority-3
